### ISSUE TITLE
BladeRF Support

### ISSUE THREAD

**Issue by dvolvox** [fairwaves/openbts-2.8#10]
Hi,

Have you try this OpenBTS build running on BladeRF?
I've generated the transceiver according to this: https://github.com/Nuand/bladeRF/wiki/Minimalistic-build-and-run-test-for-OpenBTS-5

Appears this error:
505071754.548327 139875220088640: 
Starting the system...
transceiver: no process found
ALERT 139629754185536 20:29:19.5 bladeRFDevice.cpp:100:open: Could not open bladeRF device: Invalid operation or parameter
ALERT 139629754185536 20:29:19.5 runTransceiver.cpp:119:main: Transceiver exiting...

EMERG 139875219736320 OpenBTS.cpp:134:startTransceiver: Transceiver quit with status 256. Exiting.

Broadcast message from systemd-journald@dokstation (Sun 2017-09-10 20:29:19 WEST):

openbts[17610]: EMERG 139875219736320 OpenBTS.cpp:134:startTransceiver: Transceiver quit with status 256. Exiting.

**Comment by chemeris** [comment]
Hello,

We don't support BladeRF and we're not actively supporting OpenBTS either. A recommended setup is to use UmTRX with OsmoTRX+OsmoBTS+OsmoNITB.

**Comment by yrahman** [comment]
Hi @dvolvox, @chemeris, I've similliar problem and I managed to solve this error:
`bladeRFDevice.cpp:100 open: Could not open bladeRF device: Invalid operation or parameter`
And my phone successfully connected to the OpenBTS network
But `transceiver: no process found` still occur:
```
1513494970.697944 140062499850048:
Starting the system...
transceiver: no process found

system ready

use the OpenBTSCLI utility to access CLI
rm: missing operand
Try 'rm --help' for more information.
ALERT 140062463960832 SIPEngine.cpp:406:Register: SIP REGISTER timed out; is the registration server 127.0.0.1:5064 OK?
ALERT 140062463960832 MobilityManagement.cpp:182:LocationUpdatingController: SIP registration timed out.  Is the proxy running at 127.0.0.1:5064
ALERT 140062463960832 SIPEngine.cpp:406:Register: SIP REGISTER timed out; is the registration server 127.0.0.1:5064 OK?
ALERT 140062463960832 MobilityManagement.cpp:182:LocationUpdatingController: SIP registration timed out.  Is the proxy running at 127.0.0.1:5064
ALERT 140062463960832 SIPEngine.cpp:406:Register: SIP REGISTER timed out; is the registration server 127.0.0.1:5064 OK?
ALERT 140062463960832 MobilityManagement.cpp:182:LocationUpdatingController: SIP registration timed out.  Is the proxy running at 127.0.0.1:5064
ALERT 140062463960832 SIPEngine.cpp:406:Register: SIP REGISTER timed out; is the registration server 127.0.0.1:5064 OK?
ALERT 140062463960832 MobilityManagement.cpp:182:LocationUpdatingController: SIP registration timed out.  Is the proxy running at 127.0.0.1:5064
```
And I got another problem OpenBTSCLI not working:
```
: OpenBTS> help
: sending datagram: No such file or directory
: Is the remote application running?
```
Did you know how to solve this problem?
OpenBTS and transceiver is running, but OpenBTSCLI show above message.
Any help would be appreciated

Thanks
