### ISSUE TITLE
can't access to https://wush.net/trac/rangepublic/wiki/BuildInstallRun

### ISSUE THREAD

**Issue by ibra1212** [fairwaves/openbts-2.8#12]
Hi all, I am currently working on a project with openbts and UmTRX v2.1 hardware. However, I can not access this site that requires authentication:

https://wush.net/trac/rangepublic/wiki/BuildInstallRun

Can you help me please or show me a site or I could find the installation information of OpenBTS 2.8. 

thank you in advance for your help.

**Comment by chemeris** [comment]
I would recommend you to use Osmocom for GSM - it is actively maintained and has solid UmTRX support.

**Comment by ibra1212** [comment]
Yes, I will take it into account. Thank you for your advice and for the answer.

**Comment by earwin** [comment]
Hi, @ibra1212.

I take it you got this link from our umtrx.org site.
Sorry for the confusion, we'll edit the page with what @chemeris told you.
Right now the best way to get GSM running on UmTRX is indeed the Osmocom stack.

If you still, for whatever reason, need OpenBTS, they have a site: http://openbts.org, sources: https://github.com/RangeNetworks (see openbts, and they still have a 2.8 tag), documentation: http://openbts.org/w/index.php?title=Main_Page, and a BuildInstallRun doc previously hosted on wush.net: http://openbts.org/w/index.php?title=BuildInstallRun

But take care, this is obsolete and unsupported.

**Comment by ibra1212** [comment]
thank you @earwin for the help.
